### ISSUE TITLE
Difficulty 

### ISSUE THREAD

**Issue by NorthMiners** [benjamin-wilson/public-pool#44]
How  can I set a custom Difficulty ? wont let me do it.

**Comment by yanir99** [comment]
> How can I set a custom Difficulty ? wont let me do it.

+1 for that.
Is it possible to set different ports with different minimum difficulty?

**Comment by benjamin-wilson** [comment]
In the password field you can append "d=1234"

**Comment by NorthMiners** [comment]
Nope tried that Sent from my Galaxy
-------- Original message --------From: Benjamin Wilson ***@***.***> Date: 2024-07-05  7:15 a.m.  (GMT-05:00) To: benjamin-wilson/public-pool ***@***.***> Cc: NorthMiners ***@***.***>, Author ***@***.***> Subject: Re: [benjamin-wilson/public-pool] Difficulty  (Issue #44) 
In the password field you can append "d=1234"

**Comment by yanir99** [comment]
I think some clarifications about pool difficulty is needed:
The ASIC is generating hashes regardless of the pool difficulty.
The pool difficulty is simply to tell the miner (not the ASIC) the level on which it should report back to the pool.
Example:
Pool difficulty is 1000
The ASIC generates hashes with difficulties 370, 512, 987, 403, 1050, 220, 18976 ....
from these only the 1050 and 18976 will be reported back as successful hashes to the pool - basically saying to the pool "I'm still here and generating hashes"
It's just a mean for the pool to reduce the amount of messages received from a miner in order to not overwhelm the system.

In reality all those small hashes (even above 1000 or above 1000000) means nothing, except saying "I'm still working" - because the only hash (for bitcoin) that matters will be the one solving a block (i.e. above 85000000000000).

**Comment by TylonHH** [comment]
Is this supported?
'd=2M'
